
services:
  api:
    build: .
    ports:
      - "5001:443"
      - "5000:80"
    container_name: api
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_SA_PASSWORD=password123!
    ports:
      - "1433:1433"
    container_name: sqlserver